version: 0.2

env:
  variables:
     DOTNET_SDK_VERSION: "2.2.102"
  parameter-store:
     TARGET_RUNTIME: "$ARCHITECTURE_PARAMETER"

phases:
  install:
    commands:
      - |
        if dotnet --version | grep -v "^2.2"; then
          DOTNET_SDK_DOWNLOAD_URL=https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz
          curl -sSL $DOTNET_SDK_DOWNLOAD_URL --output dotnet.tar.gz
          mkdir -p /usr/share/dotnet
          tar -zxf dotnet.tar.gz -C /usr/share/dotnet
          rm dotnet.tar.gz
          if [ ! -L /usr/bin/dotnet ]; then
            ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
          fi
          if echo ":$PATH:" | grep -v -q ":~/.dotnet/tools/:"; then
            PATH="~/.dotnet/tools/:$PATH"
          fi
        fi
  build:
    commands:
      - echo $PATH
      - echo "Building with dotnet SDK Version $(dotnet --version)"
      - echo "Building for runtime '$TARGET_RUNTIME'"
      - dotnet publish -c Release -r $TARGET_RUNTIME
      - mkdir -p build/publish
      - cp -r src/Web/bin/Release/netcoreapp2.2/$TARGET_RUNTIME/publish/* build/publish/
      - cp -r src/codedeploy/$TARGET_RUNTIME/* build/
      - PACKAGE_NAME=$CODEBUILD_BUILD_ID.zip
      - cd build
      - zip -r $PACKAGE_NAME *
      - cd ..
      - DEPLOYMENT_SUFFIX=$(echo $TARGET_RUNTIME | awk '{split($0, a, "-"); print a[2]}')
      - aws s3 cp build/$PACKAGE_NAME s3://$ARTIFACT_BUCKET/PublishedBinaries/$PACKAGE_NAME
      - aws deploy create-deployment --application-name $APPLICATION_NAME --deployment-group-name "cpu-workshop-deployment-group-$DEPLOYMENT_SUFFIX" --revision revisionType=S3,s3Location={bucket=$ARTIFACT_BUCKET,key=PublishedBinaries/$PACKAGE_NAME,bundleType=zip}
artifacts:
  files: [ '**/*' ]
  name: PublishedBinaries
  base-directory: build
