version: 0.0
os: linux
files:
  - source: .\publish
    destination: /opt/eShopOnWeb
permissions:
  - object: /opt/eShopOnWeb
    owner: ec2-user
    mode: 444
    type:
      - folder
hooks:
  ApplicationStop: 
    - location: ./scripts/stopDaemon.sh
      timeout: 60
  AfterInstall: 
    - location: ./scripts/registerDaemon.sh
      timeout: 120
  ApplicationStart: 
    - location: ./scripts/startDaemon.sh
      timeout: 60
  ValidateService: 
    - location: ./scripts/smokeTest.sh
      timeout: 60
